CREATE TABLE consultas (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    medico_id NUMBER NOT NULL,
    paciente_id NUMBER NOT NULL,
    data DATE NOT NULL,

    CONSTRAINT pk_consultas PRIMARY KEY (id),
    CONSTRAINT fk_consultas_medico_id FOREIGN KEY (medico_id) REFERENCES medicos(id),
    CONSTRAINT fk_consultas_paciente_id FOREIGN KEY (paciente_id) REFERENCES pacientes(id)
);
